### ISSUE TITLE
hook to support websocket/other transport tracing?

### ISSUE THREAD

**Issue by benmosher** [igorfv/apollo-tracing-extension#5]
Hello,

I really appreciate your extension -- the visual is a huge improvement over reading the tracing manually. Thank you!

I am working on switching my graphql transport to WebSockets, and I was bummed (but not surprised) to see the tracing is not picked up over that transport.

Is there any way I could add an explicit `ApolloLink` or something that could manually pass the tracing to the extension if it comes back over a non-traditional transport, and the extension is loaded? I can dig into code but thought I would ask first to see if you have a quick answer.

Thank you!

**Comment by igorfv** [comment]
hey @benmosher 
I'm glad you liked it. I made this extension to fill my needs while working with GraphQL so it's normal to not support everything that it could support.

Yes, we can definitely add support to WebSocket, we should be able to intercept those calls from the extension side. About manually passing the tracing info for the extension, this is also fine but that's definitely something that I wouldn't be using.

**Comment by benmosher** [comment]
Makes sense. I'll close this for now, I may take a stab at it when I circle back to websockets usage at work. Will let you know if I do. Feel free to reopen if you want to address it but I definitely understand building it out just enough to meet your own needs. Thanks!

**Comment by igorfv** [comment]
In the end, it all depends on how many nights of insomnia I have to make progress with those personal projects =(

**Comment by igorfv** [comment]
Hey @benmosher 
I'm rewriting this project and thinking of expanding it. Do you still need it / have a test server I can use to implement it?

**Comment by benmosher** [comment]
Thanks for remembering. I haven't been able to get websockets going yet. I'm still interested but I can't take advantage (yet). One reason is that I started using Urql instead of Apollo as my client  and it doesn't as readily support sending normal queries over web sockets as readily. (and it's less of an issue now that we're rolling out HTTP2 [finally])

**Comment by igorfv** [comment]
Oh, I didn't know about Urql, I'll definitely check it
